CREATE TABLE airport_management.TICKET1 (
    TICKET_NUMBER VARCHAR(20) NOT NULL,
    SOURCE VARCHAR(3),
    DESTINATION VARCHAR(3),
    DATE_OF_BOOKING DATE,
    DATE_OF_TRAVEL DATE,
    SEATNO VARCHAR(5),
    CLASS ENUM('Economy', 'Business', 'First'),
    DATE_OF_CANCELLATION DATE,
    PID INT AUTO_INCREMENT,
    PASSPORTNO VARCHAR(10),
    FOREIGN KEY (PID, PASSPORTNO) REFERENCES PASSENGER1 (PID, PASSPORTNO) ON DELETE CASCADE,
    CONSTRAINT TICKET_NO_LENGTH CHECK (LENGTH(TICKET_NUMBER) = 13));