CREATE TABLE airport_management.PASSENGER2 (
PASSPORTNO VARCHAR(10) NOT NULL, 
FNAME VARCHAR(20),
Mname VARCHAR(20),
LNAME VARCHAR(20),
ADDRESS VARCHAR(100),
PHONE INT,
AGE INT,
SEX ENUM('M', 'F'),
PRIMARY KEY(PASSPORTNO));
