CREATE TABLE airport_management.AIRPORT (
    AP_NAME VARCHAR(100) NOT NULL,
    STATE VARCHAR(28),
    COUNTRY VARCHAR(28),
    CNAME VARCHAR(28),
    PRIMARY KEY (AP_NAME),
    FOREIGN KEY (CNAME) REFERENCES CITY (CNAME) ON DELETE CASCADE
);
