CREATE TABLE airport_management.FLIGHT
(FLIGHT_CODE VARCHAR(10) NOT NULL, 
SOURCE VARCHAR(3),
DESTINATION VARCHAR(3),
ARRIVAL DATETIME,
DEPARTURE DATETIME,
STATUS ENUM('on-time', 'delayed'),
DURATION VARCHAR(30), 
FLIGHTTYPE ENUM('connecting', 'non-stop'),
AIRLINEID VARCHAR(3),
PRIMARY KEY(FLIGHT_CODE),
FOREIGN KEY(AIRLINEID) REFERENCES AIRLINE(AIRLINEID) ON DELETE CASCADE);
