CREATE TABLE airport_management.EMPLOYEE1 (
SSN INT NOT NULL AUTO_INCREMENT, 
FNAME VARCHAR(20),
MNAME VARCHAR(20),
LNAME VARCHAR(20),
ADDRESS VARCHAR(100), 
PHONE INT,
AGE INT CHECK (AGE < 60),
SEX ENUM('M', 'F'),
JOBTYPE VARCHAR(30),
AP_NAME VARCHAR(100),
PRIMARY KEY(SSN),
FOREIGN KEY(AP_NAME) REFERENCES AIRPORT(AP_NAME) ON DELETE CASCADE);
